blocks_list = ['acacia_log.png', 'acacia_log_top.png', 'acacia_planks.png', 'andesite.png', 'birch_log.png',
               'birch_log_top.png', 'birch_planks.png', 'black_terracotta.png', 'blue_ice.png', 'blue_terracotta.png',
               'bone_block_side.png', 'bone_block_top.png', 'bricks.png', 'brown_mushroom_block.png', 'brown_terracotta.png',
               'carved_pumpkin.png', 'chiseled_quartz_block.png', 'chiseled_quartz_block_top.png', 'chiseled_red_sandstone.png', 'chiseled_sandstone.png',
               'chiseled_stone_bricks.png', 'coal_block.png', 'cobblestone.png', 'cracked_stone_bricks.png', 'cut_red_sandstone.png',
               'cut_sandstone.png', 'cyan_terracotta.png', 'dark_oak_log.png', 'dark_oak_log_top.png', 'dark_oak_planks.png',
               'dark_prismarine.png', 'diamond_block.png', 'diorite.png', 'dirt.png', 'dropper_front.png',
               'end_stone.png', 'end_stone_bricks.png', 'furnace_front.png', 'furnace_side.png', 'glazed_terracotta_lime.png',
               'glowstone.png', 'gold_block.png', 'granite.png', 'grass_block_side.png', 'gravel.png',
               'gray_terracotta.png', 'green_terracotta.png', 'hay_block_side.png', 'jack_o_lantern.png', 'jungle_log.png',
               'jungle_log_top.png', 'jungle_planks.png', 'lapis_block.png', 'light_blue_terracotta.png', 'light_gray_terracotta.png',
               'lime_glazed_terracotta.png', 'lime_terracotta.png', 'magenta_terracotta.png', 'melon_side.png', 'mossy_cobblestone.png',
               'mossy_stone_bricks.png', 'mushroom_stem.png', 'netherrack.png', 'nether_bricks.png', 'nether_quartz_ore.png',
               'nether_wart_block.png', 'note_block.png', 'oak_log.png', 'oak_log_top.png', 'oak_planks.png',
               'obsidian.png', 'orange_terracotta.png', 'pink_terracotta.png', 'piston_side.png', 'piston_top.png',
               'piston_top_sticky.png', 'podzol_side.png', 'polished_andesite.png', 'polished_diorite.png', 'polished_granite.png',
               'prismarine_bricks.png', 'pumpkin_side.png', 'purple_terracotta.png', 'purpur_block.png', 'purpur_pillar.png',
               'quartz_block_bottom.png', 'quartz_block_side.png', 'quartz_block_top.png', 'quartz_pillar.png', 'quartz_pillar_top.png',
               'redstone_block.png', 'redstone_lamp.png', 'redstone_ore_e.png', 'red_mushroom_block.png', 'red_nether_bricks.png',
               'red_sand.png', 'red_sandstone.png', 'red_sandstone_bottom.png', 'red_terracotta.png', 'sand.png',
               'sandstone.png', 'sandstone_bottom.png', 'slime_block.png', 'smooth_stone.png', 'smooth_stone_slab_side.png',
               'soul_sand.png', 'sponge.png', 'spruce_log.png', 'spruce_log_top.png', 'spruce_planks.png',
               'stone.png', 'stone_bricks.png', 'terracotta.png', 'wet_sponge.png', 'white_terracotta.png',
               'yellow_terracotta.png']